### ISSUE TITLE
Small recommendation on what to include in actual repo

### ISSUE THREAD

**Issue by devandanger** [Yelp/YLTableView#2]
I'm not sure if this was due to an order of events I attempted to open the workspace or an out of date cocoapods version I was originally using but I kept getting the following error.

[!] Unable to satisfy the following requirements:

- `YLTableView (from `../`)` required by `Podfile`
- `YLTableView (= 1.0.0)` required by `Podfile.lock`

Wonder if it would be better to not include the workspace and lock.  Or include them, but include the Pods already.  Got around this issue by deleting the workspace then reinstalling the pods.

**Comment by mglidden** [comment]
Thanks for the report!

I've seen this before when using CocoaPods with local podspecs – usually, running 'pod update' gets around it. 

I just committed an update that should fix this for everyone.
