### ISSUE TITLE
Add nullability annotations to modernize YLTableView

### ISSUE THREAD

**Issue by benasher44** [Yelp/YLTableView#7]
@mglidden changed setModel to take ```nullable id``` instead of ```NSObject *``` for better swift interop in #6. We should go through and add appropriate nullability annotations throughout the rest of YLTableView to bring modernize the code a bit.

**Comment by benasher44** [comment]
@ytok Looks like you already did add nullability annotations, but there might be a few edge cases to consider. Close this out if you feel like you're satisfied with what we already have.

**Comment by ytok** [comment]
Feeling satisfied :)
